### ISSUE TITLE
Portfolio project deployment

### ISSUE THREAD

**Issue by preciousakams** [kamzzy/portfolioSetup#13]
The deployed version of my portfolio project can be found at https://kamzzy.github.io/portfolioSetup/

**Comment by t-yanick** [comment]
Hi @kamzzy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

- [OPTIONAL] Please make sure in your next milestones, you submit a link to the `Pull request` not an `issue` like you did for this particular milestone unless otherwise stated. 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
